[dependencies]
"nodejs/nodejs" = "18.*"

[[command]]
name = "server"
module = "nodejs/nodejs:node"
runner = "wasi"

[command.annotations.wasi]
main-args = ["/app/server.js"]
env = ["PORT=8080"]

[fs]
"/app" = "."